# Generated by Django 4.1.4 on 2022-12-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tests',
            old_name='languages',
            new_name='language',
        ),
    ]
