# Generated by Django 4.1.4 on 2023-01-04 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_tests', '0003_choice_question_alter_language_name_delete_tests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_tests.language'),
        ),
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_tests.language'),
        ),
    ]
