# Generated by Django 4.1.4 on 2023-01-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_tests', '0005_choice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.BooleanField(default=False, verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.BooleanField(default=False),
        ),
    ]
