# Generated by Django 4.1.4 on 2023-01-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_tests', '0007_alter_choice_choice_text_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.BooleanField(default=False),
        ),
    ]
