# Generated by Django 4.1.4 on 2023-01-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_tests', '0008_alter_choice_choice_text_alter_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
