# Generated by Django 4.1.4 on 2023-01-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_tests', '0010_question_pub_date_alter_choice_choice_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
