# Generated by Django 4.1.4 on 2023-01-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_tests', '0011_alter_choice_choice_text_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
