# Generated by Django 4.1.4 on 2023-01-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_tests', '0015_choice_correct_answer_procent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='correct_answer_procent',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer_procent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
