# Generated by Django 4.1.4 on 2023-01-16 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_tests', '0016_remove_choice_correct_answer_procent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='language',
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_tests.language')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_tests.catalog'),
        ),
    ]
