# Generated by Django 4.1.4 on 2023-02-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_tests', '0019_remove_marks_of_user_quiz_remove_marks_of_user_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question',
        ),
    ]
