# Generated by Django 4.1.4 on 2023-02-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_tests', '0020_rename_question_text_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='procent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
