# Generated by Django 4.1.4 on 2023-02-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_tests', '0021_question_procent'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_ans',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='notcorrect_ans',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
